variables:
  # Related to extension release approval process
  - name: extensionReleaseServiceConnection
    value: AzCodeReleases
  - name: extensionReleaseApprovalEnvironment # TODO: move approval to the service connections?
    value: AzCodeDeploy

  # Related to NPM release approval process
  - name: gitHubServiceConnection
    value: GitHub-AzureTools
  - name: npmReleaseApprovalEnvironment
    value: AzCodeDeploy
  - name: npmReleaseOwnerAlias
    value: azcode
  - name: npmReleaseApproverAlias
    value: jinglou

  # Test
  - name: testServiceConnection
    value: AzCodeE2ETests
