parameters:
  - extensionReleaseEnvironment: AzCodeDeploy
  - extensionReleaseServiceConnection: AzCodeReleases
  - testServiceConnection: AzCodeE2ETests
  - testBAMIVariableGroup: AzCode-BAMI-Variables
  - gitHubServiceConnection: GitHub-AzureTools
  - sdlSourcesPool:
      name: VSEngSS-MicroBuild2022-1ES
      image: server2022-microbuildVS2022-1es
      os: windows
  - buildPool:
      name: AzurePipelines-EO
      image: 1ESPT-Ubuntu22.04
      os: linux
