parameters:
  # Related to release approval process
  - extensionReleaseServiceConnection: AzCodeReleases
  - npmReleaseOwnerAlias: azcode
  - npmReleaseApproverAlias: jinglou
  - gitHubServiceConnection: GitHub-AzureTools

  # Test
  - testServiceConnection: AzCodeE2ETests

  # Pools
  - sdlSourcesPool:
      name: VSEngSS-MicroBuild2022-1ES
      image: server2022-microbuildVS2022-1es
      os: windows
  - buildPool:
      name: AzurePipelines-EO
      image: 1ESPT-Ubuntu22.04
      os: linux
