variables:
  # Related to release approval process
  - name: extensionReleaseServiceConnection
    value: AzCodeReleases
  - name: npmReleaseOwnerAlias
    value: azcode
  - name: npmReleaseApproverAlias
    value: jinglou
  - name: gitHubServiceConnection
    value: GitHub-AzureTools

  # Test
  - name: testServiceConnection
    value: AzCodeE2ETests
