variables:
  # Related to release approval process
  - name: extensionReleaseServiceConnection
    value: AzCodeReleases
  - name: npmReleaseOwnerAlias
    value: azcode
  - name: npmReleaseApproverAlias
    value: jinglou
  - name: gitHubServiceConnection
    value: GitHub-AzureTools

  # Test
  - name: testServiceConnection
    value: AzCodeE2ETests

  # Pools
  # - name: sdlSourcesPool
  #   value:
  #     name: VSEngSS-MicroBuild2022-1ES
  #     image: server2022-microbuildVS2022-1es
  #     os: windows
  # - name: buildPool
  #   value:
  #     name: AzurePipelines-EO
  #     image: 1ESPT-Ubuntu22.04
  #     os: linux
